# Generated by Django 4.0.6 on 2023-12-09 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equibasejockeys',
            fields=[
                ('equibasejockeys_id', models.AutoField(primary_key=True, serialize=False)),
                ('raceyear', models.CharField(blank=True, max_length=10, null=True)),
                ('jockeyname', models.CharField(blank=True, max_length=255, null=True)),
                ('winpercentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('equibaseidentity', models.CharField(blank=True, max_length=255, null=True)),
                ('earnings', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('equibaserank', models.CharField(blank=True, max_length=255, null=True)),
                ('place', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('equibasestarts', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('perstart', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('topthreepercent', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('equibaseshow', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('win', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('topthree', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'equibasejockeys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equibaseowners',
            fields=[
                ('equibaseowners_id', models.AutoField(primary_key=True, serialize=False)),
                ('raceyear', models.CharField(blank=True, max_length=10, null=True)),
                ('ownername', models.CharField(blank=True, max_length=255, null=True)),
                ('winpercentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('equibaseidentity', models.CharField(blank=True, max_length=255, null=True)),
                ('earnings', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('equibaserank', models.CharField(blank=True, max_length=255, null=True)),
                ('place', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('equibasestarts', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('perstart', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('topthreepercent', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('equibaseshow', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('win', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('topthree', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'equibaseowners',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equibaserunnerinfo',
            fields=[
                ('equibaserunnerinfo_id', models.AutoField(primary_key=True, serialize=False)),
                ('trackid', models.CharField(blank=True, max_length=255, null=True)),
                ('areaid', models.CharField(blank=True, max_length=255, null=True)),
                ('racedate', models.DateField(blank=True, null=True)),
                ('raceyear', models.CharField(blank=True, max_length=3, null=True)),
                ('racemonth', models.CharField(blank=True, max_length=3, null=True)),
                ('raceday', models.CharField(blank=True, max_length=3, null=True)),
                ('racenumber', models.CharField(blank=True, max_length=255, null=True)),
                ('horsename', models.CharField(blank=True, max_length=255, null=True)),
                ('horserefno', models.CharField(blank=True, max_length=255, null=True)),
                ('jockeyname', models.CharField(blank=True, max_length=255, null=True)),
                ('jockeyid', models.CharField(blank=True, max_length=255, null=True)),
                ('trainername', models.CharField(blank=True, max_length=255, null=True)),
                ('trainerid', models.CharField(blank=True, max_length=255, null=True)),
                ('ownername', models.CharField(blank=True, max_length=255, null=True)),
                ('ownerid', models.CharField(blank=True, max_length=255, null=True)),
                ('sirename', models.CharField(blank=True, max_length=255, null=True)),
                ('damname', models.CharField(blank=True, max_length=255, null=True)),
                ('damsirename', models.CharField(blank=True, max_length=255, null=True)),
                ('breeder', models.CharField(blank=True, max_length=255, null=True)),
                ('pp', models.CharField(blank=True, max_length=3, null=True)),
                ('age', models.CharField(blank=True, max_length=3, null=True)),
                ('sex', models.CharField(blank=True, max_length=2, null=True)),
                ('med', models.CharField(blank=True, max_length=3, null=True)),
                ('jockeyweight', models.CharField(blank=True, max_length=4, null=True)),
                ('mlodds', models.CharField(blank=True, max_length=255, null=True)),
                ('claim', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
            ],
            options={
                'db_table': 'equibaserunnerinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equibaserunnerinfodaily',
            fields=[
                ('equibaserunnerinfo_id', models.AutoField(primary_key=True, serialize=False)),
                ('trackid', models.CharField(blank=True, max_length=255, null=True)),
                ('areaid', models.CharField(blank=True, max_length=255, null=True)),
                ('racedate', models.DateField(blank=True, null=True)),
                ('raceyear', models.CharField(blank=True, max_length=3, null=True)),
                ('racemonth', models.CharField(blank=True, max_length=3, null=True)),
                ('raceday', models.CharField(blank=True, max_length=3, null=True)),
                ('racenumber', models.CharField(blank=True, max_length=255, null=True)),
                ('horsename', models.CharField(blank=True, max_length=255, null=True)),
                ('horserefno', models.CharField(blank=True, max_length=255, null=True)),
                ('jockeyname', models.CharField(blank=True, max_length=255, null=True)),
                ('jockeyid', models.CharField(blank=True, max_length=255, null=True)),
                ('trainername', models.CharField(blank=True, max_length=255, null=True)),
                ('trainerid', models.CharField(blank=True, max_length=255, null=True)),
                ('ownername', models.CharField(blank=True, max_length=255, null=True)),
                ('ownerid', models.CharField(blank=True, max_length=255, null=True)),
                ('sirename', models.CharField(blank=True, max_length=255, null=True)),
                ('damname', models.CharField(blank=True, max_length=255, null=True)),
                ('damsirename', models.CharField(blank=True, max_length=255, null=True)),
                ('breeder', models.CharField(blank=True, max_length=255, null=True)),
                ('pp', models.CharField(blank=True, max_length=3, null=True)),
                ('age', models.CharField(blank=True, max_length=3, null=True)),
                ('sex', models.CharField(blank=True, max_length=2, null=True)),
                ('med', models.CharField(blank=True, max_length=3, null=True)),
                ('jockeyweight', models.CharField(blank=True, max_length=4, null=True)),
                ('mlodds', models.CharField(blank=True, max_length=255, null=True)),
                ('claim', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
            ],
            options={
                'db_table': 'equibaserunnerinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equibasetrainers',
            fields=[
                ('equibasetrainers_id', models.AutoField(primary_key=True, serialize=False)),
                ('raceyear', models.CharField(blank=True, max_length=10, null=True)),
                ('trainername', models.CharField(blank=True, max_length=255, null=True)),
                ('wpsperstarter', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('earningsperstarter', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('winpercentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('equibaseidentity', models.CharField(blank=True, max_length=255, null=True)),
                ('starters', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('earnings', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('equibaserank', models.CharField(blank=True, max_length=255, null=True)),
                ('place', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('equibasestarts', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('perstart', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('topthreepercent', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('equibaseshow', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('win', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('startsperstarter', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('topthree', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'equibasetrainers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationRegistrationprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(max_length=64)),
                ('activated', models.IntegerField()),
            ],
            options={
                'db_table': 'registration_registrationprofile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationSupervisedregistrationprofile',
            fields=[
                ('registrationprofile_ptr', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='races.registrationregistrationprofile')),
            ],
            options={
                'db_table': 'registration_supervisedregistrationprofile',
                'managed': False,
            },
        ),
    ]
