# Generated by Django 4.0.6 on 2023-12-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equibasecarddaily',
            fields=[
                ('equibasecard_id', models.AutoField(primary_key=True, serialize=False)),
                ('carddate', models.DateField(blank=True, null=True)),
                ('track_id', models.CharField(blank=True, db_column='Track_Id', max_length=255, null=True)),
                ('track_name', models.CharField(blank=True, db_column='Track_Name', max_length=255, null=True)),
                ('area_id', models.CharField(blank=True, db_column='Area_Id', max_length=255, null=True)),
                ('equibasestate', models.CharField(blank=True, db_column='EquibaseState', max_length=255, null=True)),
                ('track_stage', models.CharField(blank=True, db_column='Track_Stage', max_length=255, null=True)),
                ('is_bullring', models.CharField(blank=True, max_length=1, null=True)),
                ('xml_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('isfeat', models.CharField(blank=True, max_length=1, null=True)),
                ('frank', models.CharField(blank=True, max_length=255, null=True)),
                ('race_number', models.CharField(blank=True, db_column='Race_Number', max_length=255, null=True)),
                ('equibasetext', models.TextField(blank=True, db_column='EquibaseText', null=True)),
                ('equibasedescription', models.CharField(blank=True, db_column='EquibaseDescription', max_length=255, null=True)),
                ('wager_text', models.TextField(blank=True, db_column='Wager_Text', null=True)),
                ('total_purse', models.DecimalField(blank=True, db_column='Total_Purse', decimal_places=2, max_digits=14, null=True)),
                ('post_time', models.DateTimeField(blank=True, db_column='Post_Time', null=True)),
                ('race_time', models.DateTimeField(blank=True, db_column='Race_Time', null=True)),
                ('day_eve', models.CharField(blank=True, db_column='Day_Eve', max_length=255, null=True)),
                ('race_type_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('max_claim_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('distance_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('distance_id', models.CharField(blank=True, max_length=255, null=True)),
                ('distance_in_furlong', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('course_type', models.CharField(blank=True, max_length=255, null=True)),
                ('pub_val', models.CharField(blank=True, max_length=255, null=True)),
                ('distance_display', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('surface_display', models.CharField(blank=True, max_length=255, null=True)),
                ('race_breed_type', models.CharField(blank=True, max_length=255, null=True)),
                ('race_type', models.CharField(blank=True, db_column='race_Type', max_length=255, null=True)),
                ('age_restriction', models.CharField(blank=True, max_length=255, null=True)),
                ('class_rating', models.CharField(blank=True, max_length=255, null=True)),
                ('distance_unit_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('prog_no', models.CharField(blank=True, db_column='Prog_No', max_length=255, null=True)),
                ('reg_no', models.CharField(blank=True, db_column='Reg_No', max_length=255, null=True)),
                ('horse_name', models.CharField(blank=True, db_column='Horse_Name', max_length=255, null=True)),
                ('ct', models.CharField(blank=True, max_length=255, null=True)),
                ('win_per', models.CharField(blank=True, db_column='Win_Per', max_length=255, null=True)),
                ('ml_odds', models.CharField(blank=True, db_column='ML_Odds', max_length=255, null=True)),
                ('scratch_indicator', models.CharField(blank=True, db_column='Scratch_Indicator', max_length=255, null=True)),
                ('post_pos', models.CharField(blank=True, max_length=255, null=True)),
                ('breed_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'equibasecarddaily',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='equibaserunnerinfodaily',
            table='equibaserunnerinfodaily',
        ),
    ]
